project:
  type: website
  output-dir: docs

website:
  title: "Meagan Brown"
  sidebar: true
  search: true
  navbar:
    left:
      - href: index.qmd
        text: About Meagan
      - index.qmd
      
format:
  html:
    theme: lux
    backgroundcolor: seashell
    css: styles.css
    toc: true
editor: visual

