project:
  type: website
  output-dir: docs

website:
  favicon: images/new_logo.png
  title: "Meagan Brown"
  sidebar: true
  search: false
  navbar:
    title: Meagan Brown
    logo: images/new_logo.png
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - href: posts.qmd
        text: Blog
        
    right:
      - text: Resume
        href: Brown_Meagan_Resume.pdf
      - text: CV
        href: brown_meagan_cv.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/meaganbrown/
      - icon: github
        href: https://github.com/meaganbrown
      - icon: envelope
        href: mailto:meagan_brown@bren.ucsb.edu

  page-footer: 
    background: "#4E7895"
    left: "Copyright February 2023, Meagan Brown"
    right: 
      - icon: github
        href:  https://github.com/meaganbrown
      - icon: twitter
        href: https://twitter.com/meagan__brown

format:
  html:
    theme: 
    - mystyles.scss
    page-layout: full
    mainfont: Avenir
    backgroundcolor: "#FAFAF9"
    css: styles.css
    toc: true
    editor: visual

