project:
  type: website
  output-dir: docs

website:
  favicon: images/logo4.png
  title: "Meagan Brown"
  sidebar: true
  search: false
  navbar:
    title: false
    logo: images/logo.png
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
        
    right:
      - text: Resume
        href: Brown_Meagan_Resume.pdf
      - href: posts.qmd
        text: Blog
reader-mode: true
format:
  html:
    page-layout: full
    theme: 
    - mystyle.css
    mainfont: Avenir
    backgroundcolor: seashell
    css: styles.css
    toc: true
    editor: visual

