project:
  type: website
  output-dir: docs

website:
  favicon: images/logo4.png
  title: "Meagan Brown"
  sidebar: true
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
        icon: house
      - href: about.qmd
        text: About
      - text: Resume
        href: Brown_Meagan_Resume.pdf

format:
  html:
    theme: 
    - mystyle.css
    mainfont: Avenir
    backgroundcolor: seashell
    css: styles.css
    toc: true
editor: visual

