project:
  type: website
  output-dir: docs

website:
  favicon: images/meagan_favicon.png
  title: ""
  sidebar: true
  search: false
  navbar:
    logo: images/meagan_nav.png
    left:
      - text: Home Page
        href: index.qmd
      - text: About Meagan
        href: about.qmd

    right: 
    - text: Blog
      href: posts.qmd
    - text: "Let's Get in Touch!"
      menu:
        - icon: linkedin
          text: LinkedIn
          href: https://www.linkedin.com/in/meaganbrown/
        - icon: github
          text: GitHub
          href: https://github.com/meaganbrown
        - icon: twitter
          text: twitter
          href: https://twitter.com/meagan__brown
        - icon: envelope
          text: Email
          href: mailto:meagan_brown@ucsb.edu
        - text: Resume
          href: Brown_Meagan_Resume.pdf
        - text: CV
          href: brown_meagan_cv.pdf
        

  page-footer: 
    background: "#4E7895"
    left: "© March 2023, Meagan Brown"
    right: 
      - icon: github
        href: https://github.com/meaganbrown/meaganbrown.github.io

format:
  html:
    theme: 
    - mystyles.scss
    page-layout: full
    mainfont: Avenir
    backgroundcolor: "#FAFAF9"
    css: styles.css
    toc: true
    editor: visual

