project:
  type: website
  output-dir: docs

website:
  title: "Meagan Brown"
  sidebar: true
  search: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      
format:
  html:
    theme: 
    - mystyle.css
    mainfont: Avenir
    backgroundcolor: seashell
    css: styles.css
    toc: true
editor: visual

